DataDog/dd-sdk-kotlin-multiplatform

integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPluginExt.kt, sample/androidApp/src/main/kotlin/com/datadog/kmp/android/sample/MainActivity.kt, sample/iosApp/iosApp/ContentView.swift
This PR adds tracking of network errors to the Ktor instrumentation.
=> RUM-5229: Add Ktor network errors tracking

.github/ISSUE_TEMPLATE/BugReport.yml, .github/ISSUE_TEMPLATE/CrashReport.yml, .github/ISSUE_TEMPLATE/FeatureRequest.yml, .github/ISSUE_TEMPLATE/Question.yml, .github/ISSUE_TEMPLATE/SetupIssue.yml, CONTRIBUTING.md
Apply changes proposed here https://github.com/DataDog/dd-sdk-kotlin-multiplatform/pull/88#pullrequestreview-2322583680.
=> Apply editorial fixes

integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/TracingHeaderType.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt
We had these attributes injected in the headers, but they were not propagated to the RUM resource.
=> Propagate tracing attributes to RUM

CHANGELOG.md, tools/build-plugins/src/main/kotlin/com/datadog/build/ProjectConfig.kt
This PR prepares release 0.0.3 of KMP SDK.
=> Prepare release 0.0.3

tools/build-plugins/src/main/kotlin/com/datadog/build/ProjectConfig.kt
This PR bumps dev version to 0.0.4.
=> Next dev iteration

gradle/libs.versions.toml
The main point of this PR is to have Kotlin updated to 2.0.21: this allows Xcode 16 usage.
=> Kotlin 2.0.21 & AGP 8.6.1

core/android-transitiveDependencies, features/logs/android-transitiveDependencies, features/rum/android-transitiveDependencies, features/session-replay/android-transitiveDependencies, features/webview/android-transitiveDependencies, integrations/ktor/android-transitiveDependencies
Tiny follow-up for https://github.com/DataDog/dd-sdk-kotlin-multiplatform/pull/105, I forgot to update transitive dependencies.
=> Update transitive dependencies after Kotlin 2.0.21 update

sample/androidApp/src/main/kotlin/com/datadog/kmp/android/sample/MainActivity.kt
This PR aligns the style between Android and iOS sample apps.
=> Style Android sample app similar to iOS

core/android-transitiveDependencies, core/api/commonMain/apiSurface, core/build.gradle.kts, core/src/androidMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/androidMain/kotlin/com/datadog/kmp/core/configuration/ConfigurationExt.kt, core/src/androidMain/kotlin/com/datadog/kmp/internal/BasicProxyAuthenticator.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/core/configuration/ConfigurationExtTest.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/internal/BasicProxyAuthenticatorTest.kt, core/src/appleMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/appleMain/kotlin/com/datadog/kmp/core/configuration/ConfigurationExt.kt, core/src/appleTest/kotlin/com/datadog/kmp/core/configuration/ConfigurationExtTest.kt, core/src/commonMain/kotlin/com/datadog/kmp/core/configuration/Configuration.kt, core/src/commonMain/kotlin/com/datadog/kmp/core/configuration/ProxyConfiguration.kt, gradle/libs.versions.toml
This PR brings proxy configuration support in a similar manner we have it for iOS and Android SDKs.
Closes #111.
=> RUM-7345: Support proxy

integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt
This PR fixes flaky tests for flow with a redirect.
=> Fix flaky Ktor instrumentation tests for redirects

CHANGELOG.md, tools/build-plugins/src/main/kotlin/com/datadog/build/ProjectConfig.kt
This PR prepares release 0.4.0 of Kotlin Multiplatform SDK.
=> Prepare release `0.4.0`

.gitlab-ci.yml, CHANGELOG.md
This PR merges `release/0.4.0` branch into `develop` branch.
=> Merge `release/0.4.0` branch into `develop` branch 

core/src/androidMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/DatadogExtTest.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/DatadogTest.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/config/ApplicationContextTestConfiguration.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/config/MockTestConfiguration.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/config/TestConfiguration.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/forge/ConfigurationForgeryFactory.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/forge/Configurator.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/unit/annotations/TestConfigurationsProvider.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/tools/unit/extensions/TestConfigurationExtension.kt, core/src/appleMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/appleTest/kotlin/com/datadog/kmp/DatadogExtTest.kt, tools/unit/src/commonMain/kotlin/com/datadog/tools/random/RandomUtils.kt
Basic tests for platform wrappers 
We need to be sure that wrappers will continue to follow contract 
=> RUM-4195: Supporting tests for core module

features/rum/api/appleMain/apiSurface, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/RumConfiguration.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilder.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilderTest.kt, sample/shared/src/appleMain/kotlin/com/datadog/kmp/sample/Utils.apple.kt
This PR brings support for tracking Watchdog terminations on iOS/tvOS platforms.
=> RUM-6389: Support tracking Watchdog terminations on iOS/tvOS

CHANGELOG.md, integrations/ktor/api/commonMain/apiSurface, tools/build-plugins/src/main/kotlin/com/datadog/build/ProjectConfig.kt
This PR prepares release 0.5.0 of the Kotlin Multiplatform SDK.
=> Prepare release 0.5.0

sample/androidApp/src/main/AndroidManifest.xml, sample/androidApp/src/main/res/values/strings.xml
Android sample app was missing a name, fixing that.
=> Add Android sample app name

CHANGELOG.md, integrations/ktor/api/commonMain/apiSurface
This PR merges `release/0.5.0` branch into `develop` branch.
=> Merge `release/0.5.0` branch into `develop` branch

.github/workflows/codeql-analysis.yml
Fixes the possible exploitation of the recently released [CVE](https://github.com/advisories/GHSA-vqf5-2xx6-9wfm
) 
What inspired you to submit this pull request?
Anything else we should know when reviewing?
=> Update github/codeql-action to latest version

integrations/ktor/api/commonMain/apiSurface
`apiSurface` file wasn't updated properly, fixing that.
=> Update Ktor instrumentation API surface with proper signature of the datadogKtorPlugin overload

gradle/libs.versions.toml
Small update of AGP version to 8.8.2.
=> Update AGP version to 8.8.2

CHANGELOG.md, tools/build-plugins/src/main/kotlin/com/datadog/build/ProjectConfig.kt
This PR prepares release `1.0.0` of KMP SDK.
=> Prepare release 1.0.0

CHANGELOG.md
This PR does the merge of `release/1.0.0` branch into `develop` branch.
=> Merge `release/1.0.0` branch into `develop` branch

core/api/commonMain/apiSurface, core/src/androidMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/DatadogExtTest.kt, core/src/appleMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/commonMain/kotlin/com/datadog/kmp/DatadogSite.kt
This PR brings `AP2` datacenter support.
=> RUM-10396: Add AP2 datacenter support

.gitlab-ci.yml, Dockerfile.gitlab
Use new Ubuntu version for our CI.
What inspired you to submit this pull request?
Anything else we should know when reviewing?
=> CS-71: Update base docker image to jammy

.gitlab-ci.yml
Use new ubuntu version for ci-image job.
What inspired you to submit this pull request?
Anything else we should know when reviewing?
=> CS-71: Update docker image for ci-image job to jammy

.gitlab-ci.yml, build.gradle.kts
This PR is similar to https://github.com/DataDog/dd-sdk-android/pull/2770, see more details there.
=> RUM-10655: Migrate publication to Central Publisher portal

features/rum/api/appleMain/apiSurface, features/rum/api/commonMain/apiSurface, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/RumConfiguration.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilder.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/tracking/DefaultSwiftUIRUMActionsPredicate.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/tracking/DefaultSwiftUIRUMViewsPredicate.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/tracking/SwiftUIRUMActionsPredicate.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/tracking/SwiftUIRUMViewsPredicate.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilderTest.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/tracking/DefaultSwiftUIRUMActionsPredicateTest.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/tracking/DefaultSwiftUIRUMViewsPredicateTest.kt, features/rum/src/commonMain/kotlin/com/datadog/kmp/rum/ExperimentalRumApi.kt, sample/appleApp/appleApp/ContentView.swift, sample/shared/src/appleMain/kotlin/com/datadog/kmp/sample/Utils.apple.kt, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/Utils.kt
This PR brings support of Swift UI auto-instrumentation to KMP SDK.
It is quite new and some things like button names cannot be captured automatically, so this new API is marked as experimental.
=> RUM-11444: Add automatic tracking of SwiftUI views and actions

CONTRIBUTING.md, local_ci.sh
Minor updates to reflect the current state of the project.
=> Update `CONTRIBUTING` doc and `local_ci` script
