DataDog/dd-sdk-kotlin-multiplatform

integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt
This PR brings the ability to report response size in Ktor instrumentation by reading `Content-Size` header.
However, it may be missing for the chunked response or for the streams (in that case we cannot report response size anyway), or engines like OkHttp may drop it compression-like `Content-Encoding` is applied.
In Android SDK in that case we try to read response body manually, but it seems it is somewhat complicated / dangerous to do with Ktor, because:
* Generally speaking `HttpResponse.body` doesn’t allow being read twice (see [doc](https://api.ktor.io/older/2.3.12/ktor-client/ktor-client-core/io.ktor.client.call/body.html)), meaning that if we read it in our instrumentation, client will later get an exception trying to read it as well.
* This exception is not thrown if read is done …
=> RUM-5233: Report response size in Ktor instrumentation

integrations/ktor/android-transitiveDependencies, integrations/ktor/build.gradle.kts, integrations/ktor/src/androidMain/kotlin/com/datadog/kmp/ktor/RandomExt.android.kt, integrations/ktor/src/androidMain/kotlin/com/datadog/kmp/ktor/internal/trace/DefaultTraceIdGenerator.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/trace/DefaultTraceIdGenerator.kt, integrations/ktor/src/iosMain/kotlin/com/datadog/kmp/ktor/RandomExt.ios.kt, integrations/ktor/src/iosMain/kotlin/com/datadog/kmp/ktor/internal/trace/DefaultTraceIdGenerator.kt
`kotlinx.datetime` is using `java.time` package APIs on Android ([doc](https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects)), which is available only since API 26, making application crash if it is running on the lower APIs.
This PR removes its usage in case of Android (and continue to use it in case of iOS).
On Android we will use `System.nanoTime` for now for the random seed.
Fixes #96.
=> Don't use `kotlinx.datetime` on Android

.gitlab-ci.yml
Existing Slack notifier is using old Docker runner, which is not allowed in the repo unless legacy role is enabled.
This PR makes use of Slack notifications in k8s runner.
=> Migrate Slack notifier to k8s runner

build.gradle.kts, features/rum/src/androidMain/kotlin/com/datadog/kmp/rum/tracking/ViewAttributesProvider.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/tracking/DefaultUIKitRUMViewsPredicate.kt, gradle/libs.versions.toml, integrations/ktor/api/commonMain/apiSurface, integrations/ktor/build.gradle.kts, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/RumResourceAttributesProvider.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/sampling/Sampler.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/network/NetworkClient.kt, tools/unit/src/commonMain/kotlin/com/datadog/tools/random/RandomUtils.kt
This PR adds support of RUM Resource attributes provider, allowing to add additional attributes to RUM Resources based on the request/response/error from Ktor call chain.
=> RUM-7550: Add RUM Resource attributes provider for Ktor instrumentation

integrations/ktor/api/commonMain/apiSurface, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/RumResourceAttributesProvider.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPluginExt.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/network/NetworkClient.kt
`HttpRequestBuilder.build()` has a requirement that `body` should be an instance of `OutgoingContent` ([link](https://github.com/ktorio/ktor/blob/6d26bc9c589e10cbbc5fb1e4787c8b09c329f9fc/ktor-client/ktor-client-core/common/src/io/ktor/client/request/HttpRequest.kt#L121)).
This will be the case only once `Render` pipeline stage is hit, but our `onRequest` is called earlier.
So in this PR we are building the current state of the request manually, supplying raw body before any transformations.
We could provide `HttpRequestBuilder` instead, but in the `RumResourceAttributesProvider` callbacks we want to make it clear that the value provided is expected to mutate.
Maybe, in the future, we should use `on(Send)` instead of `onRequest`, because it is called on the final pipeline stage.
- [ ] Make …
=> Avoid using `HttpRequestData` for resource attributes collection in Ktor instrumentation

.github/workflows/codeql-analysis.yml
CodeQL sometime gives the following error:
```
CodeQL detected code written in Java/Kotlin but could not process any of it
```
It may be related to the build caching in Gradle.
=> Disable Gradle build cache for CodeQL job

features/session-replay/api/commonMain/apiSurface, features/session-replay/src/androidMain/kotlin/com/datadog/kmp/sessionreplay/configuration/internal/AndroidSessionReplayConfigurationBuilder.kt, features/session-replay/src/androidUnitTest/kotlin/com/datadog/kmp/sessionreplay/configuration/internal/AndroidSessionReplayConfigurationBuilderTest.kt, features/session-replay/src/commonMain/kotlin/com/datadog/kmp/sessionreplay/configuration/SessionReplayConfiguration.kt, features/session-replay/src/commonMain/kotlin/com/datadog/kmp/sessionreplay/configuration/internal/PlatformSessionReplayConfigurationBuilder.kt, features/session-replay/src/commonTest/kotlin/com/datadog/kmp/sessionreplay/configuration/SessionReplayConfigurationBuilderTest.kt, features/session-replay/src/iosMain/kotlin/com/datadog/kmp/sessionreplay/configuration/internal/IOSSessionReplayConfigurationBuilder.kt, features/session-replay/src/iosTest/kotlin/com/datadog/kmp/sessionreplay/configuration/internal/IOSSessionReplayConfigurationBuilderTest.kt
This PR adds support of `SessionReplayConfiguration#startRecordingImmediately` API.
=> RUM-7677: Add Session Replay `startRecordingImmediately` configuration API

.gitlab-ci.yml
This PR attached Datadog Java Agent to the jobs of the Test stage, so that we can benefit from Datadog CI Visibility and can see pipeline execution and test runs there.
=> RUM-4602: Attach Datadog Java Agent to test jobs

integrations/ktor/src/androidMain/kotlin/com/datadog/kmp/ktor/RandomExt.android.kt, integrations/ktor/src/appleMain/kotlin/com/datadog/kmp/ktor/RandomExt.ios.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/RandomExt.kt
This PR switches to the usage of `SecureRandom` for Android platform, because default platform implementation is not thread-safe: if API is 34 or above, `ThreadLocalRandom` [is used](https://github.com/JetBrains/kotlin/blob/6da4e1b2134b03bcd05646ba45cf98fb5647295f/libraries/stdlib/jdk8/src/kotlin/internal/jdk8/JDK8PlatformImplementations.kt#L58), otherwise it is just `java.util.Random` [under the hood](https://github.com/JetBrains/kotlin/blob/6da4e1b2134b03bcd05646ba45cf98fb5647295f/libraries/stdlib/jvm/src/kotlin/random/PlatformRandom.kt#L50).
=> RUM-6453: Use thread-safe random

integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/RumResourceAttributesProvider.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/TracingHeaders.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/KtorPluginExt.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/test/HeadersAssert.kt, sample/androidApp/src/main/kotlin/com/datadog/kmp/android/sample/MainActivity.kt, sample/appleApp/appleApp/ContentView.swift
This change brings support of library-initiated requests (e.g. redirects) tracking in Ktor instrumentation.
Normally requests are coming from the user, but some may be initiated by the library itself (e.g. redirects, auth requests) and  we need to track them as well. This is achieved by hooking on the `on(SendingRequest)`. 
Compared to OkHttp, Ktor doesn't have a wording `application` vs `network` interceptor, but instead it has pipelines with different stages and different hooks.
The best illustration of the behavior is coming from the [official documentation](https://ktor.io/docs/client-custom-plugins.html#call-handling):
```
The SendingRequest hook is executed for every request, even if it's not initiated by a user.
For example, if a request results in a redirect, the onRequest handler …
```
=> RUM-7625: Support redirects in Ktor instrumentation

integrations/ktor/api/commonMain/apiSurface, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/TraceContextInjection.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt
This PR adds a trace injection control: API allowing to choose if tracing headers should be added only to sampled or to all outgoing requests, allowing to pass trace context to the downstream services.
=> RUM-7596: Trace context injection control

integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/TracingHeaderTypeTest.kt
This PR adds some unit tests to verify tracing headers injection.
These tests are using hardcoded values to avoid computing them programmatically, so that we don't hit any mistake during such computation.
=> RUM-6456: Add unit tests for tracing headers injection in Ktor instrumentation

integrations/ktor/api/commonMain/apiSurface, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/DatadogKtorPlugin.kt, integrations/ktor3/api/commonMain/apiSurface, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/network/NetworkClient.kt
The small quality of developer life improvement: add Ktor plugin initializer with default tracing header types (`Datadog` and `TraceContext`).
=> Add Ktor plugin initializer with default tracing header types

.github/workflows/codeql-analysis.yml
For security, third party github actions are pinned to exact commit hash instead of a floating tag version number
=> Pin github actions to commit hash

core/api/androidMain/apiSurface, core/api/appleMain/apiSurface, core/api/commonMain/apiSurface, core/src/androidMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/appleMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/commonMain/kotlin/com/datadog/kmp/Datadog.kt, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/Utils.kt
This PR brings a new API: `setUserInfo` with a mandatory user ID, to catch up with a similar change done before in the iOS and Android SDKs.
=> RUM-9486: Add setUserInfo API with mandatory user ID

core/api/androidMain/apiSurface, core/api/appleMain/apiSurface, core/api/commonMain/apiSurface, core/src/androidMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/androidUnitTest/kotlin/com/datadog/kmp/DatadogTest.kt, core/src/appleMain/kotlin/com/datadog/kmp/Datadog.kt, core/src/commonMain/kotlin/com/datadog/kmp/Datadog.kt, features/logs/api/commonMain/apiSurface, features/logs/src/androidUnitTest/kotlin/com/datadog/kmp/log/utils/forge/LogEventForgeryFactory.kt, features/logs/src/appleMain/kotlin/com/datadog/kmp/log/configuration/internal/IOSLogsConfigurationBuilder.kt, features/logs/src/appleMain/kotlin/com/datadog/kmp/log/model/internal/LogEventMappingExt.kt, features/logs/src/commonMain/json/log/log-schema.json, features/rum/api/commonMain/apiSurface, features/rum/build.gradle.kts, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/utils/forge/ActionEventForgeryFactory.kt, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/utils/forge/ErrorEventForgeryFactory.kt, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/utils/forge/LongTaskEventForgeryFactory.kt, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/utils/forge/ResourceEventForgeryFactory.kt, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/utils/forge/ViewEventForgeryFactory.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilder.kt, features/rum/src/commonMain/json/rum/_common-schema.json, sample/shared/src/commonMain/kotlin/com/datadog/kmp/sample/Utils.kt
This PR brings support for the `account`-related APIs already implemented in iOS and Android SDKs.
There is a tiny gap in the iOS SDK ObjC API for Logs: there is no `accountInfo` property for the `LogEvent`, but this is not a blocker.
=> RUM-10482: Add support for account info APIs

features/rum/api/commonMain/apiSurface, features/rum/src/commonMain/kotlin/com/datadog/kmp/rum/configuration/RumConfiguration.kt, features/rum/src/commonMain/kotlin/com/datadog/kmp/rum/configuration/RumSessionProvider.kt, features/rum/src/commonMain/kotlin/com/datadog/kmp/rum/configuration/internal/CombinedRumSessionListener.kt, features/rum/src/commonTest/kotlin/com/datadog/kmp/rum/configuration/RumConfigurationBuilderTest.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/DatadogKtorPlugin.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/TracingHeaderType.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/TracingHeaders.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/HeadersExt.kt, integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPlugin.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/TracingHeaderTypeTest.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/HeadersExtTest.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/internal/plugin/DatadogKtorPluginTest.kt, integrations/ktor/src/commonTest/kotlin/com/datadog/kmp/ktor/test/HeadersAssert.kt
This PR adds RUM Session ID to the trace context propagation headers in the Ktor instrumentation by introducing [W3C baggage](https://www.w3.org/TR/baggage) header.
This header is attached irrespective of the propagation style selected.
Implementation supports mutation of the existing `baggage` header instead of completely erasing it.
=> RUM-9966: Add RUM Session ID to the trace context propagation headers

features/logs/src/appleMain/kotlin/com/datadog/kmp/log/configuration/internal/IOSLogsConfigurationBuilder.kt, features/logs/src/appleMain/kotlin/com/datadog/kmp/log/model/internal/LogEventMappingExt.kt
This is a continuation for the fix made in iOS SDK https://github.com/DataDog/dd-sdk-ios/pull/2360.
=> RUM-10485: Add `LogEvent.accountInfo` property mapping for iOS models

features/rum/api/appleMain/apiSurface, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/RumConfiguration.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilder.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/configuration/internal/AppleRumConfigurationBuilderTest.kt
This PR adds support of memory warnings tracking for iOS.
=> RUM-11686: Add memory warnings tracking support for iOS

core/src/appleMain/kotlin/com/datadog/kmp/internal/RuntimeExt.kt, features/logs/src/appleMain/kotlin/com/datadog/kmp/log/Logs.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/Rum.kt
This PR drops an artificial delay which was used to give some time to write errors to RUM/Logs during the runtime crash, because sync methods were kindly added by @maxep in https://github.com/DataDog/dd-sdk-ios/pull/2414 which guarantee that error is written by the time these method return.
That change will reduce the percentage of unreported errors.
=> RUM-5176: Use sync methods to write error to RUM/Logs during the crash on Apple platforms

features/rum/api/commonMain/apiSurface, features/rum/src/androidMain/kotlin/com/datadog/kmp/rum/internal/RumMonitorAdapter.kt, features/rum/src/androidUnitTest/kotlin/com/datadog/kmp/rum/internal/RumMonitorAdapterTest.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/internal/DDRumMonitorProxy.kt, features/rum/src/appleMain/kotlin/com/datadog/kmp/rum/internal/RumMonitorAdapter.kt, features/rum/src/appleTest/kotlin/com/datadog/kmp/rum/internal/RumMonitorAdapterTest.kt, features/rum/src/commonMain/kotlin/com/datadog/kmp/rum/RumMonitor.kt
This PR adds `RumMonitor.addViewLoadingTime` API similar to iOS and Android SDKs.
=> RUM-6390: Add API to measure view loading time
